### ISSUE TITLE
Feature: Gallery Page

### ISSUE THREAD

**Issue by RowMur** [RowMur/st-georges-site#7]
# Epic Title

Feature: Gallery Page

## Epic Description

This feature adds a new page where we can share photos and videos of the club. 

## List of Tasks (Complete in order)

- [ ] Task 1: Collect photos/videos to include #8 
- [ ] Task 2: Implement initial layout #9 
- [ ] Task 3: Add sorting (by date) #10 
- [ ] Task 4: Add links to page in footer/header #11
